// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bookup_service;

#nullable disable

namespace bookup_service.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231003143243_Add_Columns_To_Room_And_Create_Room_Facilities")]
    partial class Add_Columns_To_Room_And_Create_Room_Facilities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("bookup_service.Models.Room", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int>("floor")
                        .HasColumnType("int");

                    b.Property<bool>("hasBathroom")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("hasFan")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("hasFridge")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("hasKitchen")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("hasTv")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("isBooked")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("bookup_service.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
